### ISSUE TITLE
Implement retries before persisting the healthcheck

### ISSUE THREAD

**Issue by paulormart** [ibp-network/ibp-monitor#61]

**Comment by dcolley** [comment]
### checkBootnode
the test creates a tmp node that waits for (currently) [300 seconds / 5 mins](https://github.com/ibp-network/ibp-monitor/blob/747f8332fdca3f7ec377808b4659a14e00d96cfa/worker/lib/f-check-bootnode.js#L21) to test if the node gets peers and starts syncing.

### checkService
the test uses @polkadot/api ws connection, and waits for [70 seconds](https://github.com/ibp-network/ibp-monitor/blob/747f8332fdca3f7ec377808b4659a14e00d96cfa/worker/lib/f-check-service.js#L123)
@polkadot/api has a built-in retry mechanism, and I think this is representative of what the user experience would be.
we could implement a retry loop, say 3 attempts?

**Comment by paulormart** [comment]
I think there is a timeout issue in @polkadot/api [ws connection](https://github.com/ibp-network/ibp-monitor/blob/747f8332fdca3f7ec377808b4659a14e00d96cfa/worker/lib/f-check-service.js#L70) - it seems that is not currently being triggered. 

So the effective timeout resorts to the one you pointed, but 70 secs i find it too much. If the monitor can't establish a ws connection within 3 attempts with a 10 seconds timeout, we should considered that endpoint offline.

**Comment by kukabi** [comment]
I think we looked into this before. @paulormart I wasn't able to find a connection timeout parameter in @polkadot/api. Underlying WS library ([ws](https://www.npmjs.com/package/ws)) does have this setting iirc, but the API doesn't utilize it. We may need to modify the API.
