### ISSUE TITLE
UI / Implement filtering in the healhcheck page

### ISSUE THREAD

**Issue by paulormart** [ibp-network/ibp-monitor#63]
![Screenshot 2023-06-08 at 10 03 01](https://github.com/ibp-network/ibp-monitor/assets/4574742/93afaa02-bbbe-4583-8ab6-5119aa545905)

It will be nice to have a filter option on top, or a check to filter for all erroneous healthchecks

**Comment by paulormart** [comment]
Having additional filter headers would be great, by status, by service, by member, by version

**Comment by dcolley** [comment]
this is now implemented in develop
